#define NOMINMAX
#include "TextRenderer.h"
#include "SpriteSetup.h"
#include "TextureManager.h"
#include "engine/render/pass/RenderWorld.h"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include "externals/json.hpp"
#include <stdexcept>
namespace MagEngine { namespace { bool IsFinite(float value){return std::isfinite(value);} bool ReadVector2(const nlohmann::json &value, MagMath::Vector2 &out){if(!value.is_array()||value.size()!=2||!value[0].is_number()||!value[1].is_number())return false; out={value[0].get<float>(),value[1].get<float>()};return IsFinite(out.x)&&IsFinite(out.y);} }
void TextRenderer::Initialize(SpriteSetup &spriteSetup,const std::string &texturePath,const std::string &metricsPath){ Finalize();spriteSetup_=&spriteSetup;texturePath_=texturePath;commands_.reserve(32);decodedCodePoints_.reserve(128);vertices_.reserve(512);indices_.reserve(768);drawRanges_.reserve(32);std::string errorMessage;if(!LoadMetrics(metricsPath,errorMessage))throw std::runtime_error("TextRenderer: invalid font metrics '"+metricsPath+"': "+errorMessage);spriteSetup_->GetTextureManager().LoadTexture(texturePath_);const auto &metadata=spriteSetup_->GetTextureManager().GetMetadata(texturePath_);if(metadata.width==0||metadata.height==0)throw std::runtime_error("TextRenderer: atlas texture has invalid size");auto *dxCore=spriteSetup_->GetDXManager();materialBuffer_=dxCore->CreateBufferResource(sizeof(MagMath::Material));materialBuffer_->Map(0,nullptr,reinterpret_cast<void **>(&materialData_));materialData_->color={1,1,1,1};materialData_->enableLighting=0;materialData_->uvTransform=MagMath::Identity4x4();const size_t transformSize=(sizeof(MagMath::TransformationMatrix)+255)&~size_t(255);transformationBuffer_=dxCore->CreateBufferResource(transformSize);transformationBuffer_->Map(0,nullptr,reinterpret_cast<void **>(&transformationData_));EnsureGpuCapacity(128);isReady_=true; }
void TextRenderer::Finalize(){isReady_=false;isRegistered_=false;commands_.clear();decodedCodePoints_.clear();vertices_.clear();indices_.clear();drawRanges_.clear();glyphs_.clear();replacementGlyph_=nullptr;mappedVertices_=nullptr;mappedIndices_=nullptr;materialData_=nullptr;transformationData_=nullptr;vertexBuffer_.Reset();indexBuffer_.Reset();materialBuffer_.Reset();transformationBuffer_.Reset();glyphCapacity_=glyphCount_=missingGlyphCount_=drawCallCount_=0;spriteSetup_=nullptr;texturePath_.clear();}
void TextRenderer::BeginFrame(){commands_.clear();vertices_.clear();indices_.clear();drawRanges_.clear();glyphCount_=missingGlyphCount_=drawCallCount_=0;isRegistered_=false;}
void TextRenderer::AddText(const TextDrawCommand &command){if(!isReady_||command.text.empty()||!IsFinite(command.scale)||command.scale<=0)return;commands_.push_back(command);}
void TextRenderer::RegisterRenderables(RenderWorld &renderWorld){if(!isReady_||isRegistered_||commands_.empty())return;BuildGeometry();if(glyphCount_==0)return;renderWorld.AddText(this);isRegistered_=true;}
bool TextRenderer::LoadMetrics(const std::string &metricsPath,std::string &errorMessage){std::ifstream stream(metricsPath);if(!stream){errorMessage="file not found";return false;}try{nlohmann::json root;stream>>root;if(!root.is_object()||!root.contains("textureWidth")||!root.contains("textureHeight")||!root.contains("glyphs")||!root["glyphs"].is_array()){errorMessage="required fields are missing";return false;}const uint32_t textureWidth=root.at("textureWidth").get<uint32_t>(),textureHeight=root.at("textureHeight").get<uint32_t>();if(textureWidth==0||textureHeight==0){errorMessage="invalid texture size";return false;}if(!root.contains("ascender")||!root.contains("descender")||!root.contains("lineHeight")){errorMessage="font metrics are missing";return false;}fontMetrics_={root.at("ascender").get<float>(),root.at("descender").get<float>(),root.at("lineHeight").get<float>()};if(!IsFinite(fontMetrics_.ascender)||!IsFinite(fontMetrics_.descender)||!IsFinite(fontMetrics_.lineHeight)||fontMetrics_.lineHeight<=0){errorMessage="invalid font metrics";return false;}for(const auto &entry:root.at("glyphs")){if(!entry.is_object()||!entry.contains("codePoint")||!entry.contains("x")||!entry.contains("y")||!entry.contains("width")||!entry.contains("height")||!entry.contains("bearingX")||!entry.contains("bearingY")||!entry.contains("advance")){errorMessage="invalid glyph entry";return false;}const uint32_t x=entry.at("x").get<uint32_t>(),y=entry.at("y").get<uint32_t>(),width=entry.at("width").get<uint32_t>(),height=entry.at("height").get<uint32_t>();GlyphMetrics glyph{};glyph.codePoint=entry.at("codePoint").get<uint32_t>();glyph.uvMin={static_cast<float>(x)/textureWidth,static_cast<float>(y)/textureHeight};glyph.uvMax={static_cast<float>(x+width)/textureWidth,static_cast<float>(y+height)/textureHeight};glyph.size={static_cast<float>(width),static_cast<float>(height)};glyph.bearing={entry.at("bearingX").get<float>(),entry.at("bearingY").get<float>()};glyph.advance=entry.at("advance").get<float>();if(x>textureWidth||y>textureHeight||width>textureWidth-x||height>textureHeight-y||!IsFinite(glyph.bearing.x)||!IsFinite(glyph.bearing.y)||!IsFinite(glyph.advance)||glyph.advance<0||glyphs_.contains(glyph.codePoint)){errorMessage="duplicate or out-of-range glyph";return false;}glyphs_.emplace(glyph.codePoint,glyph);}replacementGlyph_=FindGlyph(root.value("replacementCodePoint",0xFFFDu));if(!replacementGlyph_){errorMessage="replacement glyph is missing";return false;}return true;}catch(const std::exception &exception){glyphs_.clear();replacementGlyph_=nullptr;errorMessage=exception.what();return false;}}
bool TextRenderer::DecodeUtf8(const std::string &text){decodedCodePoints_.clear();for(size_t index=0;index<text.size();){const uint8_t lead=static_cast<uint8_t>(text[index]);if(lead<0x80){decodedCodePoints_.push_back(lead);++index;continue;}uint32_t codePoint=0,minimum=0;size_t count=0;if((lead&0xE0)==0xC0){codePoint=lead&0x1F;count=2;minimum=0x80;}else if((lead&0xF0)==0xE0){codePoint=lead&0x0F;count=3;minimum=0x800;}else if((lead&0xF8)==0xF0){codePoint=lead&0x07;count=4;minimum=0x10000;}else{decodedCodePoints_.push_back(0xFFFD);++index;continue;}if(index+count>text.size()){decodedCodePoints_.push_back(0xFFFD);++index;continue;}bool valid=true;for(size_t offset=1;offset<count;++offset){const uint8_t byte=static_cast<uint8_t>(text[index+offset]);if((byte&0xC0)!=0x80){valid=false;break;}codePoint=(codePoint<<6)|(byte&0x3F);}if(!valid||codePoint<minimum||(codePoint>=0xD800&&codePoint<=0xDFFF)||codePoint>0x10FFFF){decodedCodePoints_.push_back(0xFFFD);++index;continue;}decodedCodePoints_.push_back(codePoint);index+=count;}return true;}
void TextRenderer::BuildGeometry(){vertices_.clear();indices_.clear();drawRanges_.clear();glyphCount_=missingGlyphCount_=0;std::stable_sort(commands_.begin(),commands_.end(),[](const TextDrawCommand &a,const TextDrawCommand &b){return a.drawOrder<b.drawOrder;});for(const auto &command:commands_){DecodeUtf8(command.text);float penX=command.position.x,penY=command.position.y+fontMetrics_.ascender*command.scale;const uint32_t startIndex=static_cast<uint32_t>(indices_.size());for(uint32_t codePoint:decodedCodePoints_){if(codePoint=='\n'){penX=command.position.x;penY+=fontMetrics_.lineHeight*command.scale;continue;}const GlyphMetrics *glyph=FindGlyph(codePoint);if(!glyph){++missingGlyphCount_;glyph=replacementGlyph_;}if(!glyph)continue;if(glyphCount_>=kMaxGlyphsPerFrame)break;AppendGlyph(*glyph,penX,penY,command.scale,command.position,command.rotationRadians);++glyphCount_;penX+=glyph->advance*command.scale;}const uint32_t count=static_cast<uint32_t>(indices_.size())-startIndex;if(count)drawRanges_.push_back({startIndex,count,command.color});}EnsureGpuCapacity(glyphCount_);if(!glyphCount_)return;std::memcpy(mappedVertices_,vertices_.data(),vertices_.size()*sizeof(MagMath::VertexData));std::memcpy(mappedIndices_,indices_.data(),indices_.size()*sizeof(uint32_t));const float width=static_cast<float>(spriteSetup_->GetDXManager()->GetWinApp().GetWindowWidth()),height=static_cast<float>(spriteSetup_->GetDXManager()->GetWinApp().GetWindowHeight());transformationData_->World=MagMath::Identity4x4();transformationData_->WVP=MagMath::MakeOrthographicMatrix(0,0,width,height,0,100);}
void TextRenderer::AppendGlyph(const GlyphMetrics &g,float penX,float penY,float scale,const MagMath::Vector2 &rotationOrigin,float rotationRadians){const float left=penX+g.bearing.x*scale,top=penY-g.bearing.y*scale,right=left+g.size.x*scale,bottom=top+g.size.y*scale;const float cosine=std::cos(rotationRadians),sine=std::sin(rotationRadians);const auto Rotate=[&](float x,float y){const float localX=x-rotationOrigin.x,localY=y-rotationOrigin.y;return MagMath::Vector4{rotationOrigin.x+localX*cosine-localY*sine,rotationOrigin.y+localX*sine+localY*cosine,0.0f,1.0f};};const uint32_t base=static_cast<uint32_t>(vertices_.size());const MagMath::Vector3 normal{0,0,-1};vertices_.push_back({Rotate(left,bottom),{g.uvMin.x,g.uvMax.y},normal});vertices_.push_back({Rotate(left,top),{g.uvMin.x,g.uvMin.y},normal});vertices_.push_back({Rotate(right,bottom),{g.uvMax.x,g.uvMax.y},normal});vertices_.push_back({Rotate(right,top),{g.uvMax.x,g.uvMin.y},normal});indices_.insert(indices_.end(),{base,base+1,base+2,base+1,base+3,base+2});}
void TextRenderer::EnsureGpuCapacity(uint32_t required){if(required<=glyphCapacity_)return;glyphCapacity_=std::min(kMaxGlyphsPerFrame,(std::max)(required,glyphCapacity_?glyphCapacity_*2u:128u));auto *dxCore=spriteSetup_->GetDXManager();vertexBuffer_=dxCore->CreateBufferResource(sizeof(MagMath::VertexData)*glyphCapacity_*4);indexBuffer_=dxCore->CreateBufferResource(sizeof(uint32_t)*glyphCapacity_*6);vertexBuffer_->Map(0,nullptr,reinterpret_cast<void **>(&mappedVertices_));indexBuffer_->Map(0,nullptr,reinterpret_cast<void **>(&mappedIndices_));vertexBufferView_={vertexBuffer_->GetGPUVirtualAddress(),glyphCapacity_*4u*static_cast<UINT>(sizeof(MagMath::VertexData)),static_cast<UINT>(sizeof(MagMath::VertexData))};indexBufferView_={indexBuffer_->GetGPUVirtualAddress(),glyphCapacity_*6u*static_cast<UINT>(sizeof(uint32_t)),DXGI_FORMAT_R32_UINT};}
const GlyphMetrics *TextRenderer::FindGlyph(uint32_t codePoint)const{const auto it=glyphs_.find(codePoint);return it==glyphs_.end()?nullptr:&it->second;}
void TextRenderer::Draw(){if(!isReady_||!glyphCount_)return;spriteSetup_->CommonDrawSetup(SpriteRenderMode::Ui);auto commandList=spriteSetup_->GetDXManager()->GetCommandList();commandList->IASetVertexBuffers(0,1,&vertexBufferView_);commandList->IASetIndexBuffer(&indexBufferView_);commandList->SetGraphicsRootConstantBufferView(SpriteRootParameterBinding::kTransformation,transformationBuffer_->GetGPUVirtualAddress());commandList->SetGraphicsRootDescriptorTable(SpriteRootParameterBinding::kTexture,spriteSetup_->GetTextureManager().GetSrvHandleGPU(texturePath_));commandList->SetGraphicsRootConstantBufferView(SpriteRootParameterBinding::kDirectionalLight,spriteSetup_->GetDirectionalLightGPUVirtualAddress());for(const auto &range:drawRanges_){materialData_->color=range.color;commandList->SetGraphicsRootConstantBufferView(SpriteRootParameterBinding::kMaterial,materialBuffer_->GetGPUVirtualAddress());commandList->DrawIndexedInstanced(range.indexCount,1,range.indexOffset,0,0);++drawCallCount_;}}
}
