name: DebugBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: MagEngine.sln
  CONFIGURATION: Debug
  PLATFORM: x64

jobs:

  build:

    runs-on: windows-2022

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-


      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2


      - name: Restore
        run: nuget restore ${{ env.SOLUTION_FILE_PATH }}


      - name: Build Debug
        run: |
          msbuild $env:SOLUTION_FILE_PATH `
            /m `
            /p:Configuration=$env:CONFIGURATION `
            /p:Platform=$env:PLATFORM `
            /p:WindowsTargetPlatformVersion=10.0


      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MagEngine-Debug
          path: |
            **/x64/Debug/
            !**/*.pdb